### ISSUE TITLE
Support V3

### ISSUE THREAD

**Issue by aterreno** [aterreno/etcd-clojure#12]
At the moment this library supports only v2, it will run against an etcd server hitting the /v2 endpoint only.

**Comment by mebster** [comment]
Hi.  Any plan for v3 support?

**Comment by aterreno** [comment]
I might try to give it a shot, I rarely use clojure these days, but it can be a good chance to exercise

**Comment by aterreno** [comment]
@mebster just checked a bit the documentation on the etcd site, from a first pass it seems like they moved to proto buffers. 

https://github.com/coreos/jetcd

Is a java client built by coreos. 

Perhaps that could be a way to talk to a V3 cluster. I might try in the next week to investigate futher and see if writing a client for v3 is a full rewrite and how complex that would be.

**Comment by mebster** [comment]
That would be great.  In the meantime I'm using ZooKeeper, but would eventually like to switch to etcd.
